
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import 'gameObejctImp.sol';

//Контракт "Базовая станция" (Родитель "Игровой объект")
contract basestation is gameObejctImp {

    address[] army;

    
    mapping(address => uint) unitid;   

    constructor() public {
       
        require(tvm.pubkey() != 0, 101);
       
        require(msg.pubkey() == tvm.pubkey(), 102);
        
        tvm.accept();
                
    }
    //- получить силу защиты
    function addProtection(uint pow) public override checkOwnerAndAccept{
        health = health + pow;
    }

    //обработка гибели [вызов метода самоуничтожения + вызов метода смерти для каждого из военных юнитов базы]
    function processingdeath() public override checkOwnerAndAccept{
        if( health <=0 ){
        sendValue(address(addressenemy), 0, true);
        //вызов метода смерти для каждого из военных юнитов базы....
        for (uint256 index = 0; index < army.length; index++) {
            
        }
        }
    }

    //Добавить военный юнит (добавляет адрес военного юнита в массив или другую структуру данных)
    function addunit() public checkOwnerAndAccept{
        army.push(msg.sender);
        unitid[msg.sender] = army.length-1;
    }

    //- Убрать военный юнит
    function deleteunit(address addreswarunit) public checkOwnerAndAccept{
        delete army[unitid[addreswarunit]];
    }
    //

    
}
