
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import 'gameObejctImp.sol';
import 'warunit.sol' as unit;



//Контракт "Базовая станция" (Родитель "Игровой объект")
contract basestation is gameObejctImp {

    address[] public army;
    address public lastunit;   
    mapping(address => uint) unitid;   

    constructor() public {
       
        require(tvm.pubkey() != 0, 101);
       

        tvm.accept();
                
    }
    //- получить силу защиты
    function addProtection(uint pow) public override checkOwnerAndAccept{
        protection = protection + pow;
    }

    //обработка гибели [вызов метода самоуничтожения + вызов метода смерти для каждого из военных юнитов базы]
    function processingdeath() public override checkOwnerAndAccept{
        
        sendValue(addressenemy);
        //вызов метода смерти для каждого из военных юнитов базы....
        for (uint256 index = 0; index < army.length; index++) {
           unit.warunit(army[index]).deathisbase();
        }
        }
    //Добавить военный юнит (добавляет адрес военного юнита в массив или другую структуру данных)

    function addUnit() public checkOwnerAndAccept{
        lastunit = msg.sender;
        army.push(lastunit);
        unitid[lastunit] = army.length-1;
    }

    //- Убрать военный юнит
    function deleteunit() public checkOwnerAndAccept{
        delete army[unitid[msg.sender]];
    }
    //

    
}
