
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import "gameObejct.sol";

// This is class that describes you smart contract.
contract gameObejctImp is gameObejct {
      
    //здоровье
    uint public health = 5;
    // адрес нападоющего
    address public addressenemy;

    constructor() public {
 
        require(tvm.pubkey() != 0, 101);
      
        require(msg.pubkey() == tvm.pubkey(), 102);
  
        tvm.accept();
    }

    modifier checkOwnerAndAccept {
		// Check that message was signed with contracts key.
		require(msg.pubkey() == tvm.pubkey(), 102);
		tvm.accept();
		_;
	}

    // принять атаку определить жив ли и подсчет здлровья
    function addAtac(uint power) public override checkOwnerAndAccept{
        addressenemy = msg.sender;
        health = health - power;
        processingdeath();
    } 

     // получить силу защиты
    function addProtection(uint pow) public virtual checkOwnerAndAccept{
        health = health + pow;
    }
    // проверка на смерть
    function death() private checkOwnerAndAccept returns(bool b){
         b = (health > 0);
         return b;
    }
    //обработка гибели
    function processingdeath() public virtual checkOwnerAndAccept{
        require(death(), 103);
        sendValue(addressenemy);
    }

    //отправка всех денег атакующему и уничтожение.
    function sendValue(address dest) public view checkOwnerAndAccept{
        dest.transfer(0, true, 160);
    }
}
