
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import 'warunit.sol';
//import 'gameObejctImp.sol';

// This is class that describes you smart contract.
contract warior is warunit {

     constructor() warunit (addressbas) public {
        
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }

     //получить атаку
    function ataclevel(uint value) public override checkOwnerAndAccept{
        atac = atac + value;
    }

    //- получить силу защиты
    function addProtection(uint pow) public  override checkOwnerAndAccept{
        health = health + pow;
    }
}
